trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallZap
  steps:
  - script: |
      # Update the package list
      sudo apt-get update

      # Install OpenJDK (Java is required for ZAP)
      sudo apt-get install -y openjdk-11-jdk

      # Define the desired ZAP version
      zapVersion="2.10.0"  # Update to the desired ZAP version

      # Download and unzip ZAP
      wget https://github.com/zaproxy/zaproxy/releases/download/$zapVersion/ZAP_$zapVersion_Linux.tar.gz
      tar -xzf ZAP_$zapVersion_Linux.tar.gz -C $(Agent.ToolsDirectory)/zap

      # List the contents of the ZAP installation directory for debugging
      ls -la $(Agent.ToolsDirectory)/zap

      # Set environment variables
      echo 'export PATH=$PATH:$(Agent.ToolsDirectory)/zap/ZAP_$zapVersion' >> ~/.bashrc
    displayName: 'Install ZAP Tool'
    
- job: TestWebsiteWithZap
  dependsOn: InstallZap
  steps:
  - script: |
      chmod -R 777 ./
      docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://localhost:8089/ -g gen.conf -x OWASP-ZAP-Report.xml -r scan-report.html
      true
    displayName: 'Run ZAP Scan'


- job: PublishNUnitReport
  dependsOn: TestWebsiteWithZap
  steps:
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(Build.ArtifactStagingDirectory)/zap-report.xml'
      testRunTitle: 'ZAP Scan'
      testRunSystem: 'ZAP'
    displayName: 'Publish ZAP Test Results'
