# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: owaspzap@1
  inputs:
    threshold: '300'
    scantype: 'targetedScan'
    url: 'http://testphp.vulnweb.com/' # Replace with your target URL


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
    ArtifactName: zap
- bash: |
      #!/bin/bash

      # Install handlebars-cmd globally
      sudo npm install -g handlebars-cmd

      # Create the Handlebars template file
      cat <<EOF > ~/owasp_report.html
      <!DOCTYPE html>
      <html>
      <head>
        <title>OWASP ZAP Security Scan Report</title>
        <style>
          /* Add your CSS styles here */
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
          }
          .alert {
            border: 1px solid #FF0000;
            background-color: #FFE6E6;
            padding: 10px;
            margin-bottom: 10px;
          }
        </style>
      </head>
      <body>
        <h1>OWASP ZAP Security Scan Report</h1>
        {{#each site}}
        <div class="alert">
          <h2>{{@name}}</h2>
          <p><strong>Scan Date:</strong> {{../[@generated]}}</p>
          {{#each alerts}}
          <div class="alert">
            <h3>{{alert}}</h3>
            <p><strong>Description:</strong> {{desc}}</p>
            <p><strong>Solution:</strong> {{solution}}</p>
            <p><strong>Reference:</strong> {{reference}}</p>
            <p><strong>Instances:</strong></p>
            <ul>
              {{#each instances}}
              <li>
                <strong>URI:</strong> {{uri}}<br>
                <strong>Method:</strong> {{method}}<br>
                {{#if evidence}}<strong>Evidence:</strong> {{evidence}}<br>{{/if}}
              </li>
              {{/each}}
            </ul>
          </div>
          {{/each}}
        </div>
        {{/each}}
      </body>
      </html>
      EOF

      # Move the report to the desired location
      mv ~/owasp_report.html ~/owaspzap/report.html



  displayName: 'owasp nunit template'
  condition: always()
- bash: ' handlebars owaspzap/report.json < owaspzap/nunit-template.hbs > owaspzap/test-results.xml'
  displayName: 'generate nunit type file'
  condition: always()


- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: 'owaspzap/test-results.xml'
  condition: always()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
    ArtifactName: 'ZAP Reports'