trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ZAPScan
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet tool install -g owasp-zap-api --version 1.0.0  # Replace with the actual version you want to install
      dotnet zap-api start -v -p 8080 -d -quickurl http://testphp.vulnweb.com/
      dotnet zap-api quick-scan -t http://testphp.vulnweb.com/
      dotnet zap-api generate-report -f html -o $(Build.ArtifactStagingDirectory)/zap-report.html
      dotnet zap-api shutdown
    displayName: 'Run OWASP ZAP Scan'
    condition: succeededOrFailed()


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'zap-reports'
      publishLocation: 'pipeline'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**/*.html'  # You can specify the file pattern to match the files you want to copy.
      TargetFolder: '$(Build.ArtifactStagingDirectory)/copied-reports'  # Specify the target folder where the files will be copied.
      CleanTargetFolder: true  # Optional: Clear the target folder before copying if set to true.

# - task: owaspzap@1
#   inputs:
#     aggressivemode: false
#     threshold: '232'
#     scantype: 'targetedScan'
#     url: 'http://testphp.vulnweb.com/'
#     port: 'http://testphp.vulnweb.com/:80'
#     provideCustomContext: true
#     contextPath: '/home/vsts/work/1/s/exclude-domains.js'
#   enabled: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
#     ArtifactName: zap
# - bash: |
#    sudo npm install -g handlebars-cmd
#    cat <<EOF > owaspzap/nunit-template.hbs
#    {{#each site}}
#    <test-run
#        id="2"
#        name="Owasp test"
#        start-time="{{../[@generated]}}"  >
#        <test-suite
#            id="{{@index}}"
#            type="Assembly"
#            name="{{[@name]}}"
#            result="Failed"
#            failed="{{alerts.length}}">
#            <attachments>
#                <attachment>
#                    <filePath>owaspzap/report.html</filePath>
#                </attachment>
#            </attachments>
#        {{#each alerts}}<test-case
#            id="{{@index}}"
#            name="{{alert}}"
#            result="Failed"
#            fullname="{{alert}}"
#            time="1">
#                <failure>
#                    <message>
#                        <![CDATA[{{{desc}}}]]>
#                    </message>
#                    <stack-trace>
#                        <![CDATA[
#    Solution:
#    {{{solution}}}
#    Reference:
#    {{{reference}}}
#    instances:{{#each instances}}
#    * {{uri}}
#        - {{method}}
#        {{#if evidence}}- {{{evidence}}}{{/if}}
#                        {{/each}}]]>
#                    </stack-trace>
#                </failure>
#        </test-case>
#        {{/each}}
#        </test-suite>
#    </test-run>
#    {{/each}}
#    EOF
#   displayName: 'owasp nunit template'
#   enabled: true

# - task: PublishTestResults@2
#   displayName: 'Publish Test Results **/TEST-*.xml'
#   inputs:
#     testResultsFormat: NUnit
#     testResultsFiles: 'owaspzap/test-results.xml'
#   condition: always()
#   enabled: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
#     ArtifactName: 'ZAP Reports'
#   enabled: true
