trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ZAP_REPORT: '' # Variable to store the ZAP report content

steps:
- script: |
    # Start the OWASP ZAP Docker container
    docker run -d -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-weekly zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true

    # Wait for ZAP to start (adjust sleep time as needed)
    sleep 30
  displayName: 'Start OWASP ZAP Container'

- script: |
    # Perform a quick scan using ZAP API and store the report in a variable
    ZAP_REPORT=$(docker run -t --network host -i owasp/zap2docker-weekly zap-api-scan.py -t http://testphp.vulnweb.com/ -r /zap/wrk/zap-report.html)

    # Display the report content for verification (optional)
    echo "$ZAP_REPORT"
  displayName: 'Run OWASP ZAP Scan'

- powershell: |
    # Publish the ZAP report content as a pipeline variable
    Write-Host "##vso[task.setvariable variable=ZAP_REPORT;isOutput=true]$env:ZAP_REPORT"
  displayName: 'Publish ZAP Report as Pipeline Variable'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'zap-reports'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()


# - task: owaspzap@1
#   inputs:
#     aggressivemode: false
#     threshold: '232'
#     scantype: 'targetedScan'
#     url: 'http://testphp.vulnweb.com/'
#     port: 'http://testphp.vulnweb.com/:80'
#     provideCustomContext: true
#     contextPath: '/home/vsts/work/1/s/exclude-domains.js'
#   enabled: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
#     ArtifactName: zap
# - bash: |
#    sudo npm install -g handlebars-cmd
#    cat <<EOF > owaspzap/nunit-template.hbs
#    {{#each site}}
#    <test-run
#        id="2"
#        name="Owasp test"
#        start-time="{{../[@generated]}}"  >
#        <test-suite
#            id="{{@index}}"
#            type="Assembly"
#            name="{{[@name]}}"
#            result="Failed"
#            failed="{{alerts.length}}">
#            <attachments>
#                <attachment>
#                    <filePath>owaspzap/report.html</filePath>
#                </attachment>
#            </attachments>
#        {{#each alerts}}<test-case
#            id="{{@index}}"
#            name="{{alert}}"
#            result="Failed"
#            fullname="{{alert}}"
#            time="1">
#                <failure>
#                    <message>
#                        <![CDATA[{{{desc}}}]]>
#                    </message>
#                    <stack-trace>
#                        <![CDATA[
#    Solution:
#    {{{solution}}}
#    Reference:
#    {{{reference}}}
#    instances:{{#each instances}}
#    * {{uri}}
#        - {{method}}
#        {{#if evidence}}- {{{evidence}}}{{/if}}
#                        {{/each}}]]>
#                    </stack-trace>
#                </failure>
#        </test-case>
#        {{/each}}
#        </test-suite>
#    </test-run>
#    {{/each}}
#    EOF
#   displayName: 'owasp nunit template'
#   enabled: true

# - task: PublishTestResults@2
#   displayName: 'Publish Test Results **/TEST-*.xml'
#   inputs:
#     testResultsFormat: NUnit
#     testResultsFiles: 'owaspzap/test-results.xml'
#   condition: always()
#   enabled: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
#     ArtifactName: 'ZAP Reports'
#   enabled: true
