# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: owaspzap@1
  inputs:
    threshold: '300'
    scantype: 'targetedScan'
    url: 'http://testphp.vulnweb.com/' # Replace with your target URL


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
    ArtifactName: zap

- script: |
    dotnet tool install -g owasp-zap-api
    dotnet zap-api start -v -p 8080 -d -quickurl http://testphp.vulnweb.com/
    dotnet zap-api quick-scan -t http://testphp.vulnweb.com/
    dotnet zap-api generate-report -f html -o $(Build.ArtifactStagingDirectory)/zap-report.html
    dotnet zap-api shutdown
  displayName: 'Run OWASP ZAP Scan'
  condition: succeededOrFailed()

  condition: always()
- bash: ' handlebars owaspzap/report.json < owaspzap/nunit-template.hbs > owaspzap/test-results.xml'
  displayName: 'generate nunit type file'
  condition: always()


- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: 'owaspzap/test-results.xml'
  condition: always()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/owaspzap'
    ArtifactName: 'ZAP Reports'